/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Flex App API
 * OpenAPI spec version: v1
 */

export interface UserInfoDto {
  isAuthenticated?: boolean;
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  tenantId?: string | null;
  /** @nullable */
  tenantRole?: string | null;
  /** @nullable */
  roles?: string[] | null;
}
